### PR TITLE
Variable mean of login

### PR DESCRIPTION
**Pull request by gjuchault**

### CODE REVIEW

**Comment by gjuchault** [comment]
Fixes #30

**Comment by PymZoR** [comment]
How can we dynamically change the MoL config for each point or device ? It could be interesting to have some points not using the same MoL to log / sell. If not, there's not much use of the MoL entity :cactus:

**Comment by gjuchault** [comment]
The only way would be using the client certificate which is not "dynamic" but easily configurable.

**Comment by gjuchault** [comment]
Please open another issue @PymZoR for that

**Pull request merged**
